### ISSUE TITLE
"RegalError: The properties of an inactive agent cannot be accessed within a game cycle." on active Agent's getter

### ISSUE THREAD

**Issue by jcowman2** [regal/regal#82]
## Overview
I'm getting an error when I try and access an active agent's getter property, which returns an array.

## Description
Here is the agent in question:

```ts
export class Abilities extends Agent {
    public vision = new Ability("vision", 3, 4);
    public hearing = new Ability("hearing", 2, 3);
    public smell = new Ability("smell", 1, 2);
    public taste = new Ability("taste", 1, 2);
    public touch = new Ability("touch", 2, 3);
    public mobility = new Ability("mobility", 3, 4);
    public cognition = new Ability("cognition", 3, 4);

    public getList = () => {
        return [
            this.vision,
            this.hearing,
            this.smell,
            this.taste,
            this.touch,
            this.mobility,
            this.cognition
        ];
    };
}
```

The error occurs on this line:
```ts
for (const ab of game.state.abilities.getList()) {
```

Here is the game response:
```
{ output:
   { error: Error: RegalError: The properties of an inactive agent cannot be accessed within a game cycle.
    at Object.get (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\node_modules\regal\dist\regal.cjs.js:1602:19)
    at Proxy.Abilities.getList (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\src\agents.ts:25:18)
    at Function.common_1.on.game [as target] (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\src\actions.ts:92:51)
    at InstanceEventsImpl._executeCurrent (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\node_modules\regal\dist\regal.cjs.js:696:40)
    at InstanceEventsImpl._executeCurrent (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\node_modules\regal\dist\regal.cjs.js:704:18)
    at InstanceEventsImpl._executeCurrent (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\node_modules\regal\dist\regal.cjs.js:704:18)
    at InstanceEventsImpl.invoke (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\node_modules\regal\dist\regal.cjs.js:648:14)
    at Function.postPlayerCommand (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\node_modules\regal\dist\regal.cjs.js:1944:32)
    at Object.<anonymous> (C:\Users\Joe\Desktop\Projects\regal\ludum-dare-43\src\index.ts:61:14)
    at Module._compile (module.js:652:30),
     wasSuccessful: false } }
```

## Steps to Reproduce
1. Clone https://github.com/jcowman2/Now-Hiring
2. Checkout the `bug1` branch
3. Run `npm test`

**Comment by jcowman2** [comment]
Investigated; solution proposed in #104
